language: node_js
node_js:
  - 10

branches:
  only:
    - master 

before_install:
  - npm install -g @angular/cli --quiet

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build:prod

# addons:
#   artifacts:
#     # ⋮
#     working_dir: dist/**

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  slack: risbeacondev:4RmlqtpsVy0inPgEIjNdYjIR